---
title: "R Notebook"
output: html_notebook
---
Assignment 2:
Read in the restaurant level data: https://byuistats.github.io/M335/data/chipotle_reduced.csv

Here is a data dictionary


```{r}
library(tidyverse)
library(dplyr)
library(tidyr)
library(readr)
library("stringr")                 

data <- read_csv("C:/Users/yang/Documents/code/tutoring/Saige_r_and_python/r_assignments/chipotle_reduced.csv")
```
Use Function 2 from the previous assignment to tally across the restaurants how often each day of the week is selected as the most popular day. Then visualize the results: one chart for overall and another chart that facets by region.

```{r}
# this combines function 1 and 2 into one 
function1_2 <- function(store){ 
  data %>% 
  select(placekey, popularity_by_day) %>% 
  mutate(clean_popular = gsub("\\{|\\}", "", popularity_by_day)) %>%
  mutate(V2 = strsplit(as.character(clean_popular), ",")) %>% 
  unnest(V2) %>%
  separate(V2, c("day", "count"), ":") %>%
  mutate(clean_day = gsub('"', '', day)) %>%
  mutate(count = as.numeric(count)) %>%
  select(placekey, clean_day, count) %>%
  filter(placekey == store) %>%
  arrange(desc(count)) %>%
  top_n(1) %>%
  select(clean_day)
}

```

```{r}
# filter main data to just test and run it through above function
stores <- c("zzw-222@5vg-nwf-mp9", "22c-222@5z5-3rs-hwk", "zzw-223@5r8-fqv-xkf")

for (store in stores) {
  day = function1_2(store)
  print(day)
}


```

